Only grads can eat
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
---UGrad1 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad2 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad3 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad1 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grad4 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad3 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad1 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad2 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad0 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad3 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
Only grads can eat
Grad2 is eating...
Grad4 is eating...
Grad5 is eating...
Grads are done eating
---Only Undergrads can eat
----UGrad2 is eating...
---Undergrads done eating
